/* Auto-generated by cbindgen. Do not edit. */

#ifndef C2PA_OPENTDF_FFI_H
#define C2PA_OPENTDF_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result codes returned by FFI functions.
 */
typedef enum C2paResultCode {
    /**
     * Operation completed successfully.
     */
    SUCCESS = 0,
    /**
     * A null pointer was passed for a required argument.
     */
    NULL_POINTER = 1,
    /**
     * A string argument contained invalid UTF-8.
     */
    INVALID_UTF8 = 2,
    /**
     * C2PA signing failed.
     */
    SIGN_ERROR = 3,
    /**
     * C2PA verification / read failed.
     */
    VERIFY_ERROR = 4,
    /**
     * An internal panic was caught.
     */
    INTERNAL_ERROR = 5,
} C2paResultCode;

/**
 * Sign a media file with a C2PA manifest.
 *
 * # Safety
 * All pointer arguments must be valid C strings or null (for `error_out`).
 * The caller must free any string written to `*error_out` via [`c2pa_string_free`]
 * **before** calling this function again, or the previous string will leak.
 */
enum C2paResultCode c2pa_sign_file(const char *input_path,
                                   const char *output_path,
                                   const char *manifest_json,
                                   const char *cert_pem,
                                   const char *key_pem,
                                   char **error_out);

/**
 * Verify a C2PA manifest in a media file.
 *
 * On success, `*result_json` is set to a JSON string:
 * ```json
 * {"is_valid": true, "has_manifest": true, "manifest_json": "..."}
 * ```
 *
 * # Safety
 * The caller must free `*result_json` and `*error_out` via [`c2pa_string_free`]
 * **before** calling this function again, or previous strings will leak.
 */
enum C2paResultCode c2pa_verify_file(const char *file_path, char **result_json, char **error_out);

/**
 * Extract C2PA manifest information from a media file.
 *
 * On success, `*info_json` is set to the manifest JSON string.
 *
 * # Safety
 * The caller must free `*info_json` and `*error_out` via [`c2pa_string_free`]
 * **before** calling this function again, or previous strings will leak.
 */
enum C2paResultCode c2pa_info_file(const char *file_path, char **info_json, char **error_out);

/**
 * Free a string that was allocated by this library.
 *
 * # Safety
 * `s` must be a pointer returned by one of the FFI functions, or null.
 */
void c2pa_string_free(char *s);

#endif  /* C2PA_OPENTDF_FFI_H */
